export const errorMessages: Record<string, string> = {
  min1: 'Enter at least one character.',
  min2: 'Enter at least two characters.',
  max5: 'Enter at most five characters.',
  max50: 'Enter at most 50 characters.',
  duplicateParticipantName: 'Another participant already has this name.',
  titleRequired: 'Please enter a title.',
  invalidNumber: 'Invalid number.',
  amountRequired: 'You must enter an amount.',
  amountNotZero: 'The amount must not be zero.',
  amountTenMillion: 'The amount must be lower than 10,000,000.',
  paidByRequired: 'You must select a participant.',
  paidForMin1: 'The expense must be paid for at least one participant.',
  noZeroShares: 'All shares must be higher than 0.',
  amountSum: 'Sum of amounts must equal the expense amount.',
  percentageSum: 'Sum of percentages must equal 100.',
}
